version: '2.1'

services:
  db:
    image: mariadb:10.5
    container_name: photo-db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy

  photoview:
    image: viktorstrate/photoview:2
    container_name: photoview
    restart: always
    # ports:
    #   - 8000:80
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_API_ENDPOINT=https://photo.${DOMAIN}/api/
      - PHOTOVIEW_UI_ENDPOINT=https://photo.${DOMAIN}
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>
    volumes:
      - api_cache:/app/cache
      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /var/syncthing:/photos:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.photo.rule=Host(`photo.${DOMAIN}`)
      - traefik.http.routers.photo.middlewares=localIpOnly@file
  
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/syncthing/st-sync:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped

volumes:
  db_data:
  api_cache:

networks:
  photo-internal:
    external: false
  proxy:
    external: true
